### ISSUE TITLE
Package is abandoned

### ISSUE THREAD

**Issue by kovlcode** [andrey-helldar/laravel-ide-facades-helper#6]
Hi. I installed this package.
But composer write warning info:
Package andrey-helldar/support is abandoned, you should avoid using it. Use dragon-code/support instead.
Package dragon-code/laravel-ide-facades-helper is abandoned, you should avoid using it. No replacement was suggested.

**Comment by andrey-helldar** [comment]
Hello. Use [`Laravel Idea`](https://plugins.jetbrains.com/plugin/13441-laravel-idea) PhpStorm's plugin instead.

![image](https://user-images.githubusercontent.com/10347617/145804640-0e39de4f-a2b1-4f71-89ff-1775398087c4.png)

![image](https://user-images.githubusercontent.com/10347617/145804658-8a6be60a-7d35-4d07-a8c6-e8d6a27aa14f.png)

**Comment by andrey-helldar** [comment]
I updated the dependency to the actual one, but the given package is still abandoned.

Release: [`v1.7.0`](https://github.com/TheDragonCode/laravel-ide-facades-helper/releases/tag/v1.7.0)
